version: '2'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: >
      --deterministic
      --gasLimit 20000000
      --allowUnlimitedContractSize
      --networkId 1337
      --chainId 1337
    ports:
      - 8545:8545
  contracts:
    image: lok52/zp-contracts:latest
    depends_on:
      - ganache
  redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
    ports:
      - 6379:6379
  relayer:
    image: lok52/zp-relayer:latest
    env_file: zp-relayer/.env
    volumes:
      - relayer_tree:/app/tree.db
      - relayer_txs:/app/txs.db
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    logging:
      driver: none
  dockergen:
    image: poma/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
    volumes_from:
      - nginx
      - dockergen
    
volumes:
  relayer_tree:
  relayer_txs:
  conf:
  vhost:
  html:
  certs:
